### PR TITLE
Yet another update of Update-Modules =)

### PR DESCRIPTION
**Pull request by ScrambledBrain**
-changed check of admin privileges
-handled some logical cases
-added -ErrorAction Stop to commands in try-block, or catch will maybe never get executed regarding $ErrorActionPreference
-pimped the output for the updating process =)

### CODE REVIEW

**Comment by ScrambledBrain** [comment]
Hey Harm,
did some more work on it.
PowerShell is fun ... you know? ;D

**Review by HarmVeenstra — APPROVED** [review]
Thank you, nice!

**Comment by HarmVeenstra** [comment]
Mentioned you in the original post :)

**Comment by ScrambledBrain** [comment]
Thanks 👍

**Pull request merged**
