### PR TITLE
add: runas as an admin account

### PR DESCRIPTION
**Pull request by jambuilds**
Open the links with your admin account when your working account is a mortal (non-admin) account if needed by calling RunAs and supplying <NTDomain>\<UserName>.  This will prompt you for a password for the Credential to use with Start-Process.

Using a Credential with Start-Process requires the full path of the Browser executable to be passed into FilePath. I have attempted obtaining this using Get-Process, catering for a scenarios where the Browser is already open on the system and where there are no Browser processes running yet.  For the latter, the newly Browser window is hidden after launch so not to get in the way of the flow.  Also finds the user's default Browser when a Browser isn't specified and RunAs is for this purpose.

### CODE REVIEW

**Comment by HarmVeenstra** [comment]
I'm checking the code, it seems to work, but... Why Runas? I open my browser profile and keep that as the last browser active so that links are automatically opened in that browser. Also, I never start the browser pages for Entra ID/Azure/Intune as an Admin account. 

What is the exact use-case?

**Comment by jambuilds** [comment]
Hi.  Firstly, thanks for the script.  This is how we are setup, I guess mileage will vary here.  We have 2 accounts.  The every day work account which has its own browser profile but no access to administer any Azure resources and a second account which is used for Azure admin work.  I had created a function in my PowerShell profile which I call when I need to do any Azure admin tasks.  It runs Start-Process for the browser with a -Credential which launches a browser signed in with the profile of the second account (this doesn't mean it has any local admin privileges).  With your script I saw an opportunity to merge the two so that I can use you script but launch the browser in the context of the second account.   Hope that makes sense.  

Thought I'd share my approach in case it proves useful for others working in a similar way but I honestly have no idea if other orgs are setup in the same way, I expect some might be.

**Comment by HarmVeenstra** [comment]
I see, it makes sense for your use case. I will test some more today, and Merge it when it's ok and update the blog post, too

**Comment by HarmVeenstra** [comment]
I tried a few different approaches (Browser, filter, alias, etc.). Only Firefox seems to start automatically (but it has problems with its profile). Other browsers start in the background and don't switch to the front, and I'm wondering if it's not easier to run the script as your other account so that the browser things work. I tested that; it works fine.

I think it's the running the script as user A and invoking links to a browser in session of user B is something that might not work reliable?

**Comment by jambuilds** [comment]
Ah OK, if this doesn't work reliably then let's abandon.  I suspect it worked for me because the Run As account profile was already in place.  Thanks again for your time and consideration and will also try running the script as the other account as suggested.

**Comment by HarmVeenstra** [comment]
No problem, I think that would be the easiest/most reliable option. I will close the PR

**Comment by HarmVeenstra** [comment]
As discussed, closing and have a great 2025!

**Comment by jambuilds** [comment]
Thank you and best wishes for 2025 to you too, have good one! :)

**Pull request closed without merging**
